format = "$username$hostname$directory$git_branch$character"

[username]
show_always = true
format = "[$user@](white)"

[hostname]
ssh_only = false
format = "[$hostname](white) "

[directory]
format = "[$path](white) "
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[on $branch](bold purple) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
