#!/usr/bin/env sh

# Layout
yabai -m config layout bsp
yabai -m config window_placement second_child

# Gaps
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     16

# Comportament general
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_shadow float

# Float automat pentru app-uri care nu au sens in tile
yabai -m rule --add app="^Finder$"              manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^System Settings$"     manage=off
yabai -m rule --add app="^Activity Monitor$"    manage=off
yabai -m rule --add app="^Calculator$"          manage=off
yabai -m rule --add app="^Archive Utility$"     manage=off
