format = "$directory$git_branch$character"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " on [$branch](bold purple)"

[character]
success_symbol = " [❯](bold green)"
error_symbol = " [❯](bold red)"
