# Hardware configuration for tiny — generated by NixOS installer.
# Replace this file with the output of:
#   sudo nixos-generate-config --show-hardware-config
# or copy /etc/nixos/hardware-configuration.nix after installation.
{ ... }: {}
